name: Bug report
description: Report a bug
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: Current behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "browser/os/version"
